package com.onlinestore.model;

// Generated Dec 18, 2014 12:06:36 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FieldsProduct generated by hbm2java
 */
@Entity
@Table(name = "fields_product", schema = "public")
public class FieldsProduct implements java.io.Serializable {

	private int id;
	private Serializable serialFields;
	private Date createDate;
	private Date writeDate;
	private Boolean active;
	private Set<Category> categories = new HashSet<Category>(0);

	public FieldsProduct() {
	}

	public FieldsProduct(int id) {
		this.id = id;
	}

	public FieldsProduct(int id, Serializable serialFields, Date createDate,
			Date writeDate, Boolean active, Set<Category> categories) {
		this.id = id;
		this.serialFields = serialFields;
		this.createDate = createDate;
		this.writeDate = writeDate;
		this.active = active;
		this.categories = categories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "serial_fields")
	public Serializable getSerialFields() {
		return this.serialFields;
	}

	public void setSerialFields(Serializable serialFields) {
		this.serialFields = serialFields;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "write_date", length = 29)
	public Date getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldsProduct")
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

}
