package com.onlinestore.model;

// Generated Dec 5, 2014 12:05:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsOrder generated by hbm2java
 */
@Entity
@Table(name = "os_order", schema = "public")
public class OsOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3833737676222089168L;
	private int id;
	private OsUser osUser;
	private TransportFee transportFee;
	private Status status;
	private Tax tax;
	private String address;
	private String phone;
	private Date createDate;
	private Date writeDate;
	private Boolean active;
	private Set<OsOrderDetail> osOrderDetails = new HashSet<OsOrderDetail>(0);

	public OsOrder() {
	}

	public OsOrder(int id) {
		this.id = id;
	}

	public OsOrder(int id, OsUser osUser, TransportFee transportFee,
			Status status, Tax tax, String address, String phone,
			Date createDate, Date writeDate, Boolean active,
			Set<OsOrderDetail> osOrderDetails) {
		this.id = id;
		this.osUser = osUser;
		this.transportFee = transportFee;
		this.status = status;
		this.tax = tax;
		this.address = address;
		this.phone = phone;
		this.createDate = createDate;
		this.writeDate = writeDate;
		this.active = active;
		this.osOrderDetails = osOrderDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public OsUser getOsUser() {
		return this.osUser;
	}

	public void setOsUser(OsUser osUser) {
		this.osUser = osUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "transport_fee_id")
	public TransportFee getTransportFee() {
		return this.transportFee;
	}

	public void setTransportFee(TransportFee transportFee) {
		this.transportFee = transportFee;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status_id")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tax_id")
	public Tax getTax() {
		return this.tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 16)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "write_date", length = 29)
	public Date getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osOrder")
	public Set<OsOrderDetail> getOsOrderDetails() {
		return this.osOrderDetails;
	}

	public void setOsOrderDetails(Set<OsOrderDetail> osOrderDetails) {
		this.osOrderDetails = osOrderDetails;
	}

}
