package com.onlinestore.model;

// Generated Dec 5, 2014 12:05:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "os_order_detail", schema = "public")
public class OsOrderDetail implements java.io.Serializable {

	private int id;
	private OsOrder osOrder;
	private Product product;
	private Integer quantity;
	private Double price;
	private Date createDate;
	private Date writeDate;
	private Boolean active;

	public OsOrderDetail() {
	}

	public OsOrderDetail(int id) {
		this.id = id;
	}

	public OsOrderDetail(int id, OsOrder osOrder, Product product,
			Integer quantity, Double price, Date createDate, Date writeDate,
			Boolean active) {
		this.id = id;
		this.osOrder = osOrder;
		this.product = product;
		this.quantity = quantity;
		this.price = price;
		this.createDate = createDate;
		this.writeDate = writeDate;
		this.active = active;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public OsOrder getOsOrder() {
		return this.osOrder;
	}

	public void setOsOrder(OsOrder osOrder) {
		this.osOrder = osOrder;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "write_date", length = 29)
	public Date getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
