package com.onlinestore.model;

// Generated Nov 29, 2014 12:31:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax", schema = "public")
public class Tax implements java.io.Serializable {

	private int id;
	private String name;
	private Double value;
	private Date createDate;
	private Date writeDate;
	private Boolean active;
	private Set<OsOrder> osOrders = new HashSet<OsOrder>(0);

	public Tax() {
	}

	public Tax(int id) {
		this.id = id;
	}

	public Tax(int id, String name, Double value, Date createDate,
			Date writeDate, Boolean active, Set<OsOrder> osOrders) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.createDate = createDate;
		this.writeDate = writeDate;
		this.active = active;
		this.osOrders = osOrders;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", precision = 17, scale = 17)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "write_date", length = 29)
	public Date getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public Set<OsOrder> getOsOrders() {
		return this.osOrders;
	}

	public void setOsOrders(Set<OsOrder> osOrders) {
		this.osOrders = osOrders;
	}

}
